- id: eclipse
  name: Google Java Formatter
  description: "Runs the Google Java Formatter on Java source files. Minimum supported runtime version is JDK 11."
  language: coursier
  entry: google-java-format-jdk11
  files: \.java$
  require_serial: true
